### ISSUE TITLE
workspaces are not supported

### ISSUE THREAD

**Issue by Wxh16144** [antfu/vscode-vite#7]
I am using the workspace vscode, but the status bar does not show vite options

**Comment by antfu** [comment]
How about install `vite` under your workspace root?

**Comment by Wxh16144** [comment]
Thank you, I know my problem, my vsoce workspace has multiple projects, I must rank the vite project first；

I read the config file: https://github.com/antfu/vscode-vite/blob/main/src/config.ts#L9
